notifications:
  email: false

sudo: required
services:
  - docker

language: python
python: 3.5

env:
  global:
    - DOCKER_VERSION: 1.11.0-0~trusty
    - DOCKER_COMPOSE_VERSION: 1.7.0

before_install:  
    # list docker-engine versions
    - apt-cache madison docker-engine

    # upgrade docker-engine to specific version
    - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

    # reinstall docker-compose at specific version
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

script:
  - docker pull ebar0n/proxy-cache
  - docker run --name proxy-cache-1 -d ebar0n/proxy-cache
  - docker run --name proxy-cache-2 -d --publish 3128:3128 --publish 3141:3141 --publish 3142:3142 --volume /data/proxy-cache/squid/:/var/spool/squid3 --volume /data/proxy-cache/devpi:/var/.devpi/server --volume /data/proxy-cache/aptcacherng:/var/cache/apt-cacher-ng ebar0n/proxy-cache
  - docker inspect proxy-cache-1 | grep '"IPAddress":'
  - docker inspect proxy-cache-2 | grep '"IPAddress":'
  - cp env.example django/toolsapi/settings/.env
  - docker-compose build
  - docker-compose up -d postgres
  - docker -v
  - docker ps
  - docker-compose -v
  - docker-compose ps
  - docker-compose run --rm django isort -c -rc -df
  - docker-compose run --rm django flake8
  - docker-compose run --rm django py.test --ds=toolsapi.settings.testing
