version: '2'

services:
  postgres:
    image: postgres:9.5
    volumes:
      - /data/toolsapi/postgres:/var/lib/postgresql/data
    env_file: ./django/toolsapi/settings/.env

  nginx:
    build: ./compose/nginx
    restart: always
    env_file: ./django/toolsapi/settings/.env
    volumes:
      - ./django/public/:/srv/www/django/
      - ./run:/srv/www/run

  toolsapi-develoment:
    build:
      context: .
      dockerfile: Dockerfile-Development
    env_file: ./django/toolsapi/settings/.env
    volumes:
      - ./django:/srv/www/django
    working_dir: /srv/www/django

  toolsapi-production:
    extends:
      service: toolsapi-develoment
    build:
      dockerfile: Dockerfile-Production
    volumes:
      - ./run:/srv/www/run
    restart: always